#!/bin/bash

locale-gen en_GB.UTF-8
update-locale LANG=en_GB.UTF-8
apt-get update -y
DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade
apt-get install python3 python3-pip awscli -y
pip3 install Flask boto3
mkdir /home/ubuntu/flaskServer
cd /home/ubuntu/flaskServer
aws s3 cp --recursive s3://bvdevopsthomas/scripts/pythonweb .
FLASK_APP=server.py flask run --host=0.0.0.0 -p 80




  
